#!/usr/bin/env node

require('./tests/test-fs-fcntl');

require('./tests/test-fs-seek');

require('./tests/test-fs-flock');

require('./tests/test-fs-utime');

// for stress testing only 
if (process.argv[2] == '--stress') {
    require('./tests/test-fs-seek_stress');
    require('./tests/test-fs-flock_stress');
}
